// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_speedtest from "./routes/api/speedtest.ts";
import * as $index from "./routes/index.tsx";
import * as $SpeedTestApp from "./islands/SpeedTestApp.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/speedtest.ts": $api_speedtest,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/SpeedTestApp.tsx": $SpeedTestApp,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
